module.exports = {
  state: 'https://www.doh.wa.gov/emergencies/coronavirus',
  // stateAvailable: false,
  stateShowsCounty: true,
  count: 39,
  countyAvailable: true,
  King: 'https://www.kingcounty.gov/depts/health/communicable-diseases/disease-control/novel-coronavirus.aspx',
  Snohomish: 'https://www.snohd.org/499/COVID-19-Case-Count-Info',
  Pierce: 'https://www.tpchd.org/healthy-people/diseases/covid-19-pierce-county-cases',
  Jefferson: 'https://www.jeffersoncountypublichealth.org/1429/COVID-19',
  Island: null,
  GraysHarbor: 'http://www.healthygh.org/covid19',
  Grant: 'http://granthealth.org/updates-for-covid-19-in-grant-county/',
  Columbia: 'http://www.columbiaco.com/index.aspx?nid=18',
  Clark: 'https://www.clark.wa.gov/public-health/novel-coronavirus',
  Kitsap: 'https://kitsappublichealth.org/CommunityHealth/CoronaVirus.php',
  Kittitas: 'https://www.co.kittitas.wa.us/response/202003-covid19/default.aspx',
  Skagit: 'https://www.skagitcounty.net/Departments/HealthDiseases/coronavirus.htm',
  Thurston: 'https://www.thurstoncountywa.gov/phss/Pages/coronavirus.aspx',
  Whatcom: 'https://www.whatcomcounty.us/3329/Novel-Coronavirus-COVID-19',
  Yakima: 'https://www.yakimacounty.us/2323/Human-Coronavirus',
  Spokane: 'https://srhd.org/covid19',
};
